set_property PACKAGE_PIN W5 [get_ports {clk}]
    set_property IOSTANDARD LVCMOS33 [get_ports {clk}]


set_property PACKAGE_PIN U18 [get_ports {reset}]
    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
    

set_property PACKAGE_PIN V17 [get_ports {start}]
    set_property IOSTANDARD LVCMOS33 [get_ports {start}]


set_property PACKAGE_PIN V16 [get_ports {difficulty}]
    set_property IOSTANDARD LVCMOS33 [get_ports {difficulty}]

 
set_property PACKAGE_PIN W16 [get_ports {select_song}]
    set_property IOSTANDARD LVCMOS33 [get_ports {select_song}]    
    
set_property PACKAGE_PIN P19 [get_ports {hsync}]
    set_property IOSTANDARD LVCMOS33 [get_ports {hsync}]
set_property PACKAGE_PIN R19 [get_ports {vsync}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vsync}]


set_property PACKAGE_PIN N19 [get_ports {rgb[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]
set_property PACKAGE_PIN J19 [get_ports {rgb[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property PACKAGE_PIN H19 [get_ports {rgb[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property PACKAGE_PIN G19 [get_ports {rgb[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property PACKAGE_PIN D17 [get_ports {rgb[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property PACKAGE_PIN G17 [get_ports {rgb[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property PACKAGE_PIN H17 [get_ports {rgb[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property PACKAGE_PIN J17 [get_ports {rgb[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property PACKAGE_PIN J18 [get_ports {rgb[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property PACKAGE_PIN K18 [get_ports {rgb[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property PACKAGE_PIN L18 [get_ports {rgb[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property PACKAGE_PIN N18 [get_ports {rgb[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
    
    
    
set_property PACKAGE_PIN W7 [get_ports {cathodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[6]}]
set_property PACKAGE_PIN W6 [get_ports {cathodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[5]}]
set_property PACKAGE_PIN U8 [get_ports {cathodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[4]}]
set_property PACKAGE_PIN V8 [get_ports {cathodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {cathodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[2]}]
set_property PACKAGE_PIN V5 [get_ports {cathodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[1]}]
set_property PACKAGE_PIN U7 [get_ports {cathodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[0]}]

set_property PACKAGE_PIN U2 [get_ports {anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]

set_property PACKAGE_PIN G3 [get_ports {note_buttons[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[7]}]
set_property PACKAGE_PIN H2 [get_ports {note_buttons[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[6]}]
set_property PACKAGE_PIN K2 [get_ports {note_buttons[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[5]}]
set_property PACKAGE_PIN H1 [get_ports {note_buttons[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[4]}]
set_property PACKAGE_PIN G2 [get_ports {note_buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[3]}]
set_property PACKAGE_PIN J2 [get_ports {note_buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[2]}]
set_property PACKAGE_PIN L2 [get_ports {note_buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[1]}]
set_property PACKAGE_PIN J1 [get_ports {note_buttons[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note_buttons[0]}]

set_property PACKAGE_PIN A14 [get_ports {audio_output}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_output}]